name: Close Inactive Issues
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Close inactive issues
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO="${{ github.repository }}"
          OWNER="${{ github.repository_owner }}"
          
          echo "Checking for inactive issues..."
          CLOSED_ISSUES=$(curl -s -X GET -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$OWNER/$REPO/issues?state=open" | \
            jq 'map(select(.comments == 0 and .updated_at < (now - 14*24*60*60))) | .[].number')
          
          for ISSUE_NUMBER in $CLOSED_ISSUES; do
            echo "Closing issue #$ISSUE_NUMBER..."
            curl -s -X POST -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/comments" \
              -d '{"body":"This issue has been automatically closed due to inactivity."}'
              
            curl -s -X PATCH -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER" \
              -d '{"state":"closed"}'
          done
          
          echo "Inactive issues closed successfully."
